[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xdc9656"
index = 16

[[colors.indexed_colors]]
color = "0xa16946"
index = 17

[[colors.indexed_colors]]
color = "0x282828"
index = 18

[[colors.indexed_colors]]
color = "0x383838"
index = 19

[[colors.indexed_colors]]
color = "0xb8b8b8"
index = 20

[[colors.indexed_colors]]
color = "0xe8e8e8"
index = 21

[colors.bright]
black = "0x585858"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xf8f8f8"
yellow = "0xf7ca88"

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[colors.hints.end]
background = "0x585858"
foreground = "0x181818"

[colors.hints.start]
background = "0xf7ca88"
foreground = "0x181818"

[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[cursor.style]
blinking = "On"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "L"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[window]
dynamic_padding = false
dynamic_title = true

[window.padding]
x = 2
y = 2
